import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  const [Fname, setFname] = useState(null);
  const [Lname, setLname] = useState(null);
  const [Ms, setMs] = useState(null);
  const [CodeSubject, setCodeSubject] = useState(null);
  const [Number, setNumber] = useState(null);
  const [Room, setRoom] = useState(null);

  const [DataResult1, setDataResult1] = useState(null);
  const [DataResult2, setDataResult2] = useState(null);

  useEffect(() => {
    console.log(Fname);
  }, [Fname]);

  const submit = (e) => {
    e.preventDefault();
    const check =
      Ms !== null &&
      CodeSubject !== null &&
      Fname !== null &&
      Lname !== null &&
      Number !== null &&
      Room !== null;

    if (check) {
      send_data({
        mr: Ms,
        fname: Fname,
        lname: Lname,
        room: Room,
        number: Number,
        codeSubject: CodeSubject,
        typeNote: "สมุดจด",
        details: 3,
      }).then((data) =>setDataResult1(data));
      send_data({
        mr: Ms,
        fname: Fname,
        lname: Lname,
        room: Room,
        number: Number,
        codeSubject: CodeSubject,
        typeNote: "สมุดแบบฝึกหัด",
        details: 3,
      }).then((data) => setDataResult2(data));
    }
  };

  const send_data = async (obj) => {
    let data = await JSON.stringify(obj);

    let config = await {
      method: "post",
      url: "/api/generator",
      headers: {
        "Content-Type": "application/json",
      },
      data: data,
    };

    let res = await axios(config);
    let result = await res.data;
    return result;
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container mt-5">
        <div className="card">
          <div className="card-body">
            <h5 className="card-title">Generator Name</h5>
            <p className="card-text p-2">
              <form onSubmit={submit}>
                <div classname="mb-3">
                  <select
                    class="form-select mb-3"
                    aria-label="Default select example"
                    onChange={(v) =>
                      v.target.value !== "เลือกคำนำหน้า"
                        ? setMs(v.target.value)
                        : setMs(null)
                    }
                  >
                    <option>เลือกคำนำหน้า</option>
                    <option value={"นาย"}>นาย</option>
                    <option value={"นางสาว"}>นางสาว</option>
                  </select>
                  <select
                    class="form-select"
                    aria-label="Default select example"
                    onChange={(v) =>
                      v.target.value !== "เลือกรหัสวิชา"
                        ? setCodeSubject(v.target.value)
                        : setCodeSubject(null)
                    }
                  >
                    <option>เลือกรหัสวิชา</option>
                    <option value={"ว30203"}>ว30203 (ภาคเรียนที่ 1)</option>
                    <option value={"ว30204"}>ว30204 (ภาคเรียนที่ 2)</option>
                  </select>
                  <hr />
                  <div className="row mt-3">
                    <div className="col">
                      <div className="mb-3">
                        <label>
                          ชื่อ (
                          <strong className="text-danger">ไม่มีคำนำหน้า</strong>
                          )
                        </label>
                        <input
                          placeholder="ตัวอย่าง : รักเรียน"
                          onChange={(v) => setFname(v.target.value)}
                          type="text"
                          value={Fname}
                          className="form-control"
                        />
                      </div>
                      <div>
                        <label>นามสกุล</label>
                        <input
                          value={Lname}
                          onChange={(v) => setLname(v.target.value)}
                          placeholder="ตัวอย่าง : ทำดี"
                          type="text"
                          className="form-control"
                        />
                      </div>
                    </div>

                    <div className="col">
                      <div className="mb-3">
                        <label>เลขที่</label>
                        <input
                          value={Number}
                          onChange={(v) => setNumber(v.target.value)}
                          placeholder="ตัวอย่าง : 16"
                          type="number"
                          className="form-control"
                        />
                      </div>
                      <div>
                        <label>ห้อง</label>
                        <input
                          value={Room}
                          onChange={(v) => setRoom(v.target.value)}
                          placeholder="ห้อง"
                          type="number"
                          className="form-control"
                          defaultValue
                        />
                      </div>
                    </div>
                  </div>
                  <hr />
                  <div className="d-grid gap-2">
                    <button type="submit" className=" btn btn-success">
                      Generator
                    </button>
                  </div>
                </div>
              </form>
            </p>
            <hr />
            {DataResult1 !== null && DataResult2 !== null ? 
            <div>
              <img className="w-100" src={DataResult1.image} />
              <img className="w-100" src={DataResult2.image} />
            </div> : ""}
          </div>
        </div>
      </div>
    </div>
  );
}
